// <auto-generated />
using System;
using BeanShare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeanShare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BeanShareDbContext))]
    [Migration("20250926084811_AddCoffeeStockTables")]
    partial class AddCoffeeStockTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId")
                        .IsUnique();

                    b.ToTable("CoffeeStocks", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.Space.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Spaces", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchasedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeStockId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PurchasedAt");

                    b.ToTable("Purchases", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.StockLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeStockId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("StockLevels", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.Space.Space", b =>
                {
                    b.OwnsMany("BeanShare.Domain.Entities.SpaceMembership", "Members", b1 =>
                        {
                            b1.Property<Guid>("SpaceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("UserId");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("SpaceId", "UserId");

                            b1.ToTable("SpaceMemberships", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpaceId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", null)
                        .WithMany("Purchases")
                        .HasForeignKey("CoffeeStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BeanShare.Domain.ValueObjects.CoffeeProduct", "Product", b1 =>
                        {
                            b1.Property<Guid>("PurchaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ProductBrand");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ProductName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductType");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Weight", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("PurchaseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Grams")
                                .HasColumnType("decimal(10,1)")
                                .HasColumnName("QuantityGrams");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Money", "Cost", b1 =>
                        {
                            b1.Property<Guid>("PurchaseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CostCurrency");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.Navigation("Cost")
                        .IsRequired();

                    b.Navigation("Product")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.StockLevel", b =>
                {
                    b.HasOne("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", null)
                        .WithMany("StockLevels")
                        .HasForeignKey("CoffeeStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BeanShare.Domain.ValueObjects.CoffeeProduct", "Product", b1 =>
                        {
                            b1.Property<Guid>("StockLevelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ProductBrand");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ProductName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductType");

                            b1.HasKey("StockLevelId");

                            b1.ToTable("StockLevels");

                            b1.WithOwner()
                                .HasForeignKey("StockLevelId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Weight", "TotalConsumed", b1 =>
                        {
                            b1.Property<Guid>("StockLevelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Grams")
                                .HasColumnType("decimal(10,1)")
                                .HasColumnName("TotalConsumedGrams");

                            b1.HasKey("StockLevelId");

                            b1.ToTable("StockLevels");

                            b1.WithOwner()
                                .HasForeignKey("StockLevelId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Weight", "TotalPurchased", b1 =>
                        {
                            b1.Property<Guid>("StockLevelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Grams")
                                .HasColumnType("decimal(10,1)")
                                .HasColumnName("TotalPurchasedGrams");

                            b1.HasKey("StockLevelId");

                            b1.ToTable("StockLevels");

                            b1.WithOwner()
                                .HasForeignKey("StockLevelId");
                        });

                    b.Navigation("Product")
                        .IsRequired();

                    b.Navigation("TotalConsumed")
                        .IsRequired();

                    b.Navigation("TotalPurchased")
                        .IsRequired();
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("StockLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
