// <auto-generated />
using System;
using BeanShare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeanShare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BeanShareDbContext))]
    [Migration("20251216215436_AddBillingPeriodIdToConsumptions")]
    partial class AddBillingPeriodIdToConsumptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeanShare.Domain.Aggregates.BillingPeriod.BillingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("ClosedBy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SettledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("SettledBy");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SpaceId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("SpaceId", "StartDate", "EndDate");

                    b.ToTable("BillingPeriods", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId")
                        .IsUnique();

                    b.ToTable("CoffeeStocks", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchasedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeStockId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PurchasedAt");

                    b.ToTable("Purchases", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.StockLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoffeeStockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeStockId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("StockLevels", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.Settlement.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("BillingPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("BillingPeriodId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GeneratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("GeneratedBy");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SpaceId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BillingPeriodId")
                        .IsUnique();

                    b.HasIndex("SpaceId");

                    b.ToTable("Settlements", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.Space.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Spaces", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.ConsumptionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillingPeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("uuid");

                    b.Property<string>("PresetName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("QuantityGrams");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedAt")
                        .HasDatabaseName("IX_Consumptions_ConsumedAt");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("IX_Consumptions_SpaceId");

                    b.HasIndex("SpaceId", "ConsumedAt")
                        .HasDatabaseName("IX_Consumptions_SpaceId_ConsumedAt");

                    b.ToTable("Consumptions", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("TargetCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyCode", "TargetCurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ExchangeRates_Base_Target");

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.GlobalPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DefaultCoffeeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("DefaultGrams")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("DefaultGrams");

                    b.Property<string>("DefaultPreparation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_GlobalPresets_DisplayOrder");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_GlobalPresets_IsActive");

                    b.ToTable("GlobalPresets", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notifications_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_UserId_IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.PresetRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CoffeeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("DefaultGrams")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("DefaultGrams");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("IX_PresetRecipes_SpaceId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PresetRecipes_UserId");

                    b.HasIndex("SpaceId", "UsageCount")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PresetRecipes_SpaceId_UsageCount");

                    b.ToTable("PresetRecipes", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.SpaceGlobalPresetConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("GlobalPresetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("IX_SpaceGlobalPresetConfigs_SpaceId");

                    b.HasIndex("SpaceId", "GlobalPresetId")
                        .IsUnique()
                        .HasDatabaseName("IX_SpaceGlobalPresetConfigs_SpaceId_GlobalPresetId");

                    b.ToTable("SpaceGlobalPresetConfigs", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PreferredCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Provider_ProviderUserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.UserPresetFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GlobalPresetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PresetRecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SpaceId")
                        .HasDatabaseName("IX_UserPresetFavorites_UserId_SpaceId");

                    b.HasIndex("UserId", "SpaceId", "GlobalPresetId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPresetFavorites_UserId_SpaceId_GlobalPresetId")
                        .HasFilter("\"GlobalPresetId\" IS NOT NULL");

                    b.HasIndex("UserId", "SpaceId", "PresetRecipeId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPresetFavorites_UserId_SpaceId_PresetRecipeId")
                        .HasFilter("\"PresetRecipeId\" IS NOT NULL");

                    b.ToTable("UserPresetFavorites", (string)null);
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.Purchase", b =>
                {
                    b.HasOne("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", null)
                        .WithMany("Purchases")
                        .HasForeignKey("CoffeeStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Money", "Cost", b1 =>
                        {
                            b1.Property<Guid>("PurchaseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("CostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CostCurrency");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.CoffeeProduct", "Product", b1 =>
                        {
                            b1.Property<Guid>("PurchaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ProductBrand");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ProductName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductType");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Weight", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("PurchaseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Grams")
                                .HasColumnType("decimal(10,1)")
                                .HasColumnName("QuantityGrams");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.Navigation("Cost")
                        .IsRequired();

                    b.Navigation("Product")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.StockLevel", b =>
                {
                    b.HasOne("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", null)
                        .WithMany("StockLevels")
                        .HasForeignKey("CoffeeStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BeanShare.Domain.ValueObjects.CoffeeProduct", "Product", b1 =>
                        {
                            b1.Property<Guid>("StockLevelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ProductBrand");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ProductName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductType");

                            b1.HasKey("StockLevelId");

                            b1.ToTable("StockLevels");

                            b1.WithOwner()
                                .HasForeignKey("StockLevelId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Weight", "TotalConsumed", b1 =>
                        {
                            b1.Property<Guid>("StockLevelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Grams")
                                .HasColumnType("decimal(10,1)")
                                .HasColumnName("TotalConsumedGrams");

                            b1.HasKey("StockLevelId");

                            b1.ToTable("StockLevels");

                            b1.WithOwner()
                                .HasForeignKey("StockLevelId");
                        });

                    b.OwnsOne("BeanShare.Domain.ValueObjects.Weight", "TotalPurchased", b1 =>
                        {
                            b1.Property<Guid>("StockLevelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Grams")
                                .HasColumnType("decimal(10,1)")
                                .HasColumnName("TotalPurchasedGrams");

                            b1.HasKey("StockLevelId");

                            b1.ToTable("StockLevels");

                            b1.WithOwner()
                                .HasForeignKey("StockLevelId");
                        });

                    b.Navigation("Product")
                        .IsRequired();

                    b.Navigation("TotalConsumed")
                        .IsRequired();

                    b.Navigation("TotalPurchased")
                        .IsRequired();
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.Settlement.Settlement", b =>
                {
                    b.OwnsMany("BeanShare.Domain.Aggregates.Settlement.SettlementLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("UserId");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("TotalCoffeeGrams")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal?>("TotalMilkMl")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("SettlementId", "UserId");

                            b1.ToTable("SettlementLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");

                            b1.OwnsOne("BeanShare.Domain.ValueObjects.Money", "AmountDue", b2 =>
                                {
                                    b2.Property<Guid>("SettlementLineSettlementId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SettlementLineUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("AmountDue");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("SettlementLineSettlementId", "SettlementLineUserId");

                                    b2.ToTable("SettlementLines");

                                    b2.WithOwner()
                                        .HasForeignKey("SettlementLineSettlementId", "SettlementLineUserId");
                                });

                            b1.OwnsOne("BeanShare.Domain.ValueObjects.PaymentConfirmation", "Confirmation", b2 =>
                                {
                                    b2.Property<Guid>("SettlementLineSettlementId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SettlementLineUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("ConfirmedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("ConfirmedAt");

                                    b2.Property<Guid>("ConfirmedBy")
                                        .HasColumnType("uuid")
                                        .HasColumnName("ConfirmedBy");

                                    b2.HasKey("SettlementLineSettlementId", "SettlementLineUserId");

                                    b2.ToTable("SettlementLines");

                                    b2.WithOwner()
                                        .HasForeignKey("SettlementLineSettlementId", "SettlementLineUserId");
                                });

                            b1.Navigation("AmountDue")
                                .IsRequired();

                            b1.Navigation("Confirmation");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.Space.Space", b =>
                {
                    b.OwnsMany("BeanShare.Domain.Aggregates.Space.SpaceMembership", "Members", b1 =>
                        {
                            b1.Property<Guid>("SpaceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("UserId");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("SpaceId", "UserId");

                            b1.ToTable("SpaceMemberships", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpaceId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("BeanShare.Domain.Entities.ConsumptionEntry", b =>
                {
                    b.OwnsOne("BeanShare.Domain.ValueObjects.CoffeeProduct", "Product", b1 =>
                        {
                            b1.Property<Guid>("ConsumptionEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ProductBrand");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ProductName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductType");

                            b1.HasKey("ConsumptionEntryId");

                            b1.ToTable("Consumptions");

                            b1.WithOwner()
                                .HasForeignKey("ConsumptionEntryId");
                        });

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("BeanShare.Domain.Aggregates.CoffeeStock.CoffeeStock", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("StockLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
