using BeanShare.Application.Constants;
using BeanShare.Application.Features.Settlement.Dtos;
using ClosedXML.Excel;

namespace BeanShare.Infrastructure.Services.Documents;

/// <summary>
/// Generates Excel settlement reports using ClosedXML.
/// Styling values are defined in <see cref="ExcelStyleConstants"/>.
/// </summary>
public sealed class SettlementExcelGenerator
{
    private static readonly XLColor PrimaryXlColor = XLColor.FromHtml(ExcelStyleConstants.PrimaryColor);
    private static readonly XLColor LightBgXlColor = XLColor.FromHtml(ExcelStyleConstants.LightBackgroundColor);
    private static readonly XLColor AlternateRowXlColor = XLColor.FromHtml(ExcelStyleConstants.AlternateRowColor);
    private static readonly XLColor PaidRowXlColor = XLColor.FromHtml(ExcelStyleConstants.PaidRowColor);
    private static readonly XLColor TotalRowXlColor = XLColor.FromHtml(ExcelStyleConstants.TotalRowColor);

    public byte[] GenerateExcel(SettlementReportData data)
    {
        using var workbook = new XLWorkbook();

        CreateSummarySheet(workbook, data);
        CreateDetailsSheet(workbook, data);

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    private void CreateSummarySheet(XLWorkbook workbook, SettlementReportData data)
    {
        var ws = workbook.Worksheets.Add("Summary");

        ws.Cell("A1").Value = "BeanShare Settlement Report";
        ws.Cell("A1").Style
            .Font.SetBold(true)
            .Font.SetFontSize(ExcelStyleConstants.TitleFontSize)
            .Font.SetFontColor(PrimaryXlColor);
        ws.Range("A1:D1").Merge();

        var row = 3;
        SetLabelValue(ws, ref row, "Space:", data.SpaceName);
        SetLabelValue(ws, ref row, "Billing Period:", data.BillingPeriodName);

        ws.Cell($"A{row}").Value = "Period Start:";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = data.PeriodStart;
        ws.Cell($"B{row}").Style.DateFormat.Format = "dd MMM yyyy";
        row++;

        ws.Cell($"A{row}").Value = "Period End:";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = data.PeriodEnd;
        ws.Cell($"B{row}").Style.DateFormat.Format = "dd MMM yyyy";
        row++;

        ws.Cell($"A{row}").Value = "Generated At:";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = data.GeneratedAt;
        ws.Cell($"B{row}").Style.DateFormat.Format = "dd MMM yyyy HH:mm";
        row++;

        SetLabelValue(ws, ref row, "Generated By:", data.GeneratedByName);

        row++;
        ComposeSectionHeader(ws, row, "Summary");
        row++;

        ws.Cell($"A{row}").Value = "Total Amount:";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = data.TotalAmount;
        ws.Cell($"B{row}").Style.NumberFormat.Format = ExcelStyleConstants.CurrencyFormat;
        ws.Cell($"C{row}").Value = data.Currency;
        row++;

        SetLabelValue(ws, ref row, "Participants:", data.TotalParticipants);

        ws.Cell($"A{row}").Value = "Total Coffee (g):";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = data.TotalCoffeeGrams;
        ws.Cell($"B{row}").Style.NumberFormat.Format = "#,##0.0";
        row++;

        ws.Cell($"A{row}").Value = "Total Milk (ml):";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = data.TotalMilkMl;
        ws.Cell($"B{row}").Style.NumberFormat.Format = "#,##0.0";
        row++;

        row++;
        var paidCount = data.Lines.Count(l => l.IsPaid);
        var pendingCount = data.Lines.Count - paidCount;

        ComposeSectionHeader(ws, row, "Payment Status");
        row++;

        ws.Cell($"A{row}").Value = "Paid:";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = paidCount;
        ws.Cell($"B{row}").Style.Font.SetFontColor(XLColor.Green);
        row++;

        ws.Cell($"A{row}").Value = "Pending:";
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").Value = pendingCount;
        if (pendingCount > 0)
        {
            ws.Cell($"B{row}").Style.Font.SetFontColor(XLColor.Orange);
        }

        ws.Columns().AdjustToContents();
    }

    private void CreateDetailsSheet(XLWorkbook workbook, SettlementReportData data)
    {
        var ws = workbook.Worksheets.Add("Details");

        var headers = new[] { "Member", "Email", "Coffee (g)", "Milk (ml)", "Share %", "Amount Due", "Currency", "Status", "Confirmed By", "Confirmed At" };

        for (var i = 0; i < headers.Length; i++)
        {
            ws.Cell(1, i + 1).Value = headers[i];
            ws.Cell(1, i + 1).Style
                .Font.SetBold(true)
                .Font.SetFontColor(XLColor.White)
                .Fill.SetBackgroundColor(PrimaryXlColor)
                .Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);
        }

        var row = 2;
        foreach (var line in data.Lines.OrderByDescending(l => l.AmountDue))
        {
            ws.Cell(row, 1).Value = line.UserName;
            ws.Cell(row, 2).Value = line.UserEmail;
            ws.Cell(row, 3).Value = line.CoffeeGrams;
            ws.Cell(row, 3).Style.NumberFormat.Format = "#,##0.0";
            ws.Cell(row, 4).Value = line.MilkMl ?? 0;
            ws.Cell(row, 4).Style.NumberFormat.Format = "#,##0.0";
            ws.Cell(row, 5).Value = line.ConsumptionPercentage;
            ws.Cell(row, 5).Style.NumberFormat.Format = "#,##0.00\"%\"";
            ws.Cell(row, 6).Value = line.AmountDue;
            ws.Cell(row, 6).Style.NumberFormat.Format = ExcelStyleConstants.CurrencyFormat;
            ws.Cell(row, 7).Value = data.Currency;
            ws.Cell(row, 8).Value = line.IsPaid ? "Paid" : "Pending";
            ws.Cell(row, 8).Style.Font.SetFontColor(line.IsPaid ? XLColor.Green : XLColor.Orange);
            ws.Cell(row, 9).Value = line.ConfirmedByName ?? "";
            ws.Cell(row, 10).Value = line.ConfirmedAt?.ToString("dd MMM yyyy HH:mm") ?? "";

            if (row % 2 == 0)
            {
                ws.Range(row, 1, row, headers.Length).Style.Fill.BackgroundColor = AlternateRowXlColor;
            }

            if (line.IsPaid)
            {
                ws.Range(row, 1, row, headers.Length).Style.Fill.BackgroundColor = PaidRowXlColor;
            }

            row++;
        }

        if (row > 2)
        {
            var dataRange = ws.Range(1, 1, row - 1, headers.Length);
            dataRange.Style.Border.SetOutsideBorder(XLBorderStyleValues.Thin);
            dataRange.Style.Border.SetInsideBorder(XLBorderStyleValues.Thin);

            ws.Cell(row, 1).Value = "TOTAL";
            ws.Cell(row, 1).Style.Font.SetBold(true);
            ws.Cell(row, 3).FormulaA1 = $"=SUM(C2:C{row - 1})";
            ws.Cell(row, 3).Style.Font.SetBold(true).NumberFormat.Format = "#,##0.0";
            ws.Cell(row, 4).FormulaA1 = $"=SUM(D2:D{row - 1})";
            ws.Cell(row, 4).Style.Font.SetBold(true).NumberFormat.Format = "#,##0.0";
            ws.Cell(row, 5).FormulaA1 = $"=SUM(E2:E{row - 1})";
            ws.Cell(row, 5).Style.Font.SetBold(true).NumberFormat.Format = "#,##0.00\"%\"";
            ws.Cell(row, 6).FormulaA1 = $"=SUM(F2:F{row - 1})";
            ws.Cell(row, 6).Style.Font.SetBold(true).NumberFormat.Format = ExcelStyleConstants.CurrencyFormat;
            ws.Range(row, 1, row, headers.Length).Style.Fill.BackgroundColor = TotalRowXlColor;
        }

        ws.Columns().AdjustToContents();
        ws.SheetView.FreezeRows(1);
    }

    private static void SetLabelValue(IXLWorksheet ws, ref int row, string label, object value)
    {
        ws.Cell($"A{row}").Value = label;
        ws.Cell($"A{row}").Style.Font.SetBold(true);
        ws.Cell($"B{row}").SetValue(XLCellValue.FromObject(value));
        row++;
    }

    private static void ComposeSectionHeader(IXLWorksheet ws, int row, string title)
    {
        ws.Cell($"A{row}").Value = title;
        ws.Cell($"A{row}").Style.Font.SetBold(true)
            .Font.SetFontSize(ExcelStyleConstants.SectionHeaderFontSize);
        ws.Range($"A{row}:D{row}").Merge();
        ws.Cell($"A{row}").Style.Fill.BackgroundColor = LightBgXlColor;
    }
}
