<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="System.IO.Packaging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\BeanShare.Application\BeanShare.Application.csproj" />
    <ProjectReference Include="..\BeanShare.Infrastructure.Persistence\BeanShare.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\BeanShare.Infrastructure.Identity\BeanShare.Infrastructure.Identity.csproj" />
    <ProjectReference Include="..\BeanShare.Infrastructure.Communication\BeanShare.Infrastructure.Communication.csproj" />
  </ItemGroup>

</Project>