namespace BeanShare.Infrastructure.Communication.Templates;

/// <summary>
/// Email template for settlement notifications.
/// </summary>
public static class SettlementEmailTemplate
{
    /// <summary>
    /// Generates the HTML email body for a settlement notification.
    /// </summary>
    public static string GenerateHtml(
        string userName,
        string spaceName,
        string billingPeriodName,
        DateTime periodStart,
        DateTime periodEnd,
        decimal amountDue,
        string currency,
        decimal consumptionPercentage,
        string? appUrl = null)
    {
        var viewDetailsLink = !string.IsNullOrEmpty(appUrl)
            ? $"<p style=\"text-align: center;\"><a href=\"{appUrl}\" style=\"display: inline-block; padding: 12px 24px; background-color: #795548; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;\">View Details</a></p>"
            : "";

        return $"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>BeanShare Settlement</title>
            </head>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
                <div style="background-color: #795548; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                    <h1 style="margin: 0; font-size: 24px;">BeanShare</h1>
                    <p style="margin: 5px 0 0 0; font-size: 14px;">Settlement Ready</p>
                </div>

                <div style="background-color: #f5f5f5; padding: 20px; border-radius: 0 0 8px 8px;">
                    <p>Hi {userName},</p>

                    <p>A new settlement has been generated for <strong>{spaceName}</strong>.</p>

                    <div style="background-color: white; border: 1px solid #ddd; border-radius: 4px; padding: 15px; margin: 20px 0;">
                        <h3 style="margin-top: 0; color: #795548;">Settlement Summary</h3>
                        <table style="width: 100%; border-collapse: collapse;">
                            <tr>
                                <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Billing Period:</strong></td>
                                <td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right;">{billingPeriodName}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Period:</strong></td>
                                <td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right;">{periodStart:dd MMM yyyy} - {periodEnd:dd MMM yyyy}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Your Share:</strong></td>
                                <td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right;">{consumptionPercentage:N1}%</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px 0;"><strong>Amount Due:</strong></td>
                                <td style="padding: 8px 0; text-align: right; font-size: 18px; color: #795548;"><strong>{amountDue:N2} {currency}</strong></td>
                            </tr>
                        </table>
                    </div>

                    {viewDetailsLink}

                    <p style="color: #666; font-size: 12px; margin-top: 20px;">
                        Please confirm your payment once completed. If you have any questions, contact your space administrator.
                    </p>
                </div>

                <div style="text-align: center; padding: 15px; color: #999; font-size: 12px;">
                    <p>Generated by BeanShare</p>
                </div>
            </body>
            </html>
            """;
    }

    /// <summary>
    /// Generates the plain text email body for a settlement notification.
    /// </summary>
    public static string GeneratePlainText(
        string userName,
        string spaceName,
        string billingPeriodName,
        DateTime periodStart,
        DateTime periodEnd,
        decimal amountDue,
        string currency,
        decimal consumptionPercentage)
    {
        return $"""
            BeanShare Settlement
            ====================

            Hi {userName},

            A new settlement has been generated for {spaceName}.

            Settlement Summary
            ------------------
            Billing Period: {billingPeriodName}
            Period: {periodStart:dd MMM yyyy} - {periodEnd:dd MMM yyyy}
            Your Share: {consumptionPercentage:N1}%
            Amount Due: {amountDue:N2} {currency}

            Please confirm your payment once completed. If you have any questions, contact your space administrator.

            --
            Generated by BeanShare
            """;
    }
}
